spring:
  config:
    import:
      - optional:file:env/backend/.env[.properties]
      - optional:file:/mugit/yaml/config/application.properties

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  web:
    resources:
      static-locations: "file://${UPLOAD_PATH}/"

upload-path: ${UPLOAD_PATH}

server:
  port: 8090