spring:
  config:
    import:
      - optional:file:env/backend/.env[.properties]
      - optional:file:/mugit/yaml/config/application.properties

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

upload-path: ${UPLOAD_PATH}

server:
  port: 8090