spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  application:
    name: mugit

  profiles:
    include: swagger

  config:
    import:
      - optional:file:env/backend/.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_DOMAIN}:${DB_PORT}/${DB_NAME}
    username: ${DB_ID}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

jwt:
  secret-key: ${JWT_SECRET_KEY}
  period:
    access-token: 86400000 # 1일
    refresh-token: 2419200000 #4주

cookie:
  domain: localhost
  period:
    access-token: 86400 # 1일
    refresh-token: 2419200 # 4주

